[build]
command = "npm install"

[deploy]
startCommand = "npx prisma generate && npx prisma db push && npx ts-node src/scripts/seed.ts && npx ts-node src/index.ts"

[env]
NODE_ENV = "production"